# Generated by Django 5.1.3 on 2024-11-27 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_necesario', models.IntegerField()),
                ('pokemon_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='pokemones.pokemon')),
                ('pokemon_evolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucion', to='pokemones.pokemon')),
            ],
        ),
    ]
